-- Thêm các trường còn thiếu vào bảng nhankhau
ALTER TABLE nhankhau 
ADD COLUMN IF NOT EXISTS NoiSinh VARCHAR(255),
ADD COLUMN IF NOT EXISTS NguyenQuan VARCHAR(255),
ADD COLUMN IF NOT EXISTS QuocTich VARCHAR(100) DEFAULT 'Việt Nam',
ADD COLUMN IF NOT EXISTS DiaChiThuongTru VARCHAR(500),
ADD COLUMN IF NOT EXISTS SoDienThoai VARCHAR(20),
ADD COLUMN IF NOT EXISTS Email VARCHAR(255),
ADD COLUMN IF NOT EXISTS TrinhDoHocVan VARCHAR(100);
